-- Создаем пользователя alm_qort
CREATE USER alm_qort
    IDENTIFIED BY alm_qort
    DEFAULT TABLESPACE DATA
    TEMPORARY TABLESPACE TEMP
    PROFILE DEFAULT
    ACCOUNT UNLOCK;

GRANT CONNECT TO alm_qort;
GRANT RESOURCE TO alm_qort;
ALTER USER alm_qort DEFAULT ROLE ALL;

GRANT UNLIMITED TABLESPACE TO alm_qort;

GRANT CREATE VIEW TO alm_qort;
GRANT CREATE MATERIALIZED VIEW TO alm_qort;

-- Создаем пользователя alm_qort_app
CREATE USER alm_qort_app
    IDENTIFIED BY alm_qort_app
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

GRANT CONNECT TO alm_qort_app;
GRANT RESOURCE TO alm_qort_app;
ALTER USER alm_qort_app DEFAULT ROLE ALL;

GRANT UNLIMITED TABLESPACE TO alm_qort_app;
