spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=finance_acc
    hikari.maximum-pool-size: 5
    username: finance_acc
    password: finance_acc
  liquibase:
    contexts: test

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    ru.nirs: DEBUG